AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  CustomEventBus: 
    Type: AWS::Events::EventBus
    Properties: 
      Name: "CustomEventBus"

  NameTestFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: booking/functions/ # folder where your main program resides
      Handler: bootstrap
      Runtime: provided.al2
      Architectures: [arm64]

  SearchFlightFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: flight-management/functions/ # folder where your main program resides
      Handler: bootstrap
      Runtime: provided.al2
      Architectures: [arm64]

  APIGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      DefinitionBody:
        swagger: "2.0"
        info:
          title: "APIGateway"
        paths:
          /createEvent:
            post:
              consumes:
                - application/json
              produces:
                - application/json
              parameters: []
              responses: {}
              x-amazon-apigateway-integration:
                type: aws
                httpMethod: POST
                uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${NameTestFunction.Arn}/invocations"
                paths:

          /searchFlight:
            post:
              consumes:
                - application/json
              produces:
                - application/json
              parameters: []
              responses: {}
              x-amazon-apigateway-integration:
                type: aws
                httpMethod: POST
                uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${SearchFlightFunction.Arn}/invocations"

  APIGatewayPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt NameTestFunction.Arn
      Principal: apigateway.amazonaws.com

  APIGatewayPermissionSearchFlight:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt SearchFlightFunction.Arn
      Principal: apigateway.amazonaws.com

  EventRule:
    Type: AWS::Events::Rule
    Properties:
      EventBusName: !Ref CustomEventBus
      EventPattern:
        source:
          - "api.gateway"
        detail-type:
          - "API Gateway Request"
      Targets:
        - Arn: !GetAtt NameTestFunction.Arn
          Id: "InvokeLambdaFunction"

  EventRuleSearchFlight:
    Type: AWS::Events::Rule
    Properties:
      EventBusName: !Ref CustomEventBus
      EventPattern:
        source:
          - "api.gateway"
        detail-type:
          - "API Gateway Request"
      Targets:
        - Arn: !GetAtt SearchFlightFunction.Arn
          Id: "InvokeLambdaFunction"
          

